### ISSUE TITLE
How to position on second screen

### ISSUE THREAD

**Issue by tchoblond59** [igorw765/Regulus-Spotify#1]
Hello i have two 1920*1080 monitor, my main monitor is on my left and i want to display it on the second one on my right.
How can i do this ?

Great work, i love the design btw

**Comment by kijimoshi1337** [comment]
Sadly it's not supported in the current version. You might try the instructions provided [here](https://askubuntu.com/questions/965737/conky-dual-screen-positioning). Thanks for your kind words!
